# Generated by Django 5.2.4 on 2025-07-24 14:58

from django.db import migrations

def create_superuser(apps, schema_editor):
    from django.contrib.auth import get_user_model

    User = get_user_model()

    # Only create if no superuser exists 
    if not User.objects.filter(is_superuser=True).exists():
        superuser = User.objects.create_superuser(
            username="example_username",
            email="example@example.com",
            password="examplepassword",
        )
        print(f"Superuser '{superuser.username}' created successfully")
    else:
        print("Superuser already exists, skipping creation")


def reverse_create_superuser(apps, schema_editor):
    from django.contrib.auth import get_user_model

    User = get_user_model()
    User.objects.filter(username="example_username").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_superuser, reverse_create_superuser),
    ]
